<a href="https://colab.research.google.com/github/Rahena79/Pandas-DataFrame/blob/main/Untitled8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving student.csv to student (1).csv

In [ ]:
pd.read_csv('student.csv')

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78     NaN
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
df = pd.read_csv('student.csv')
print(df)

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78     NaN
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
27  28    Rojj Base  Seven    86  female
28  29  Tess Played  Seven    55    male
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
df.shape

TypeError: 'tuple' object is not callable

In [ ]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
df.describe()

              id       mark
count  35.000000  35.000000
mean   18.000000  74.657143
std    10.246951  16.401117
min     1.000000  18.000000
25%     9.500000  62.500000
50%    18.000000  79.000000
75%    26.500000  88.000000
max    35.000000  96.000000

In [ ]:
df["name"]

0        John Deo
1        Max Ruin
2          Arnold
3      Krish Star
4       John Mike
5       Alex John
6     My John Rob
7          Asruid
8         Tes Qry
9        Big John
10         Ronald
11          Recky
12            Kty
13           Bigy
14       Tade Row
15          Gimmy
16          Tumyu
17          Honny
18          Tinny
19         Jackly
20     Babby John
21         Reggid
22          Herod
23      Tiddy Now
24       Giff Tow
25         Crelea
26            NaN
27      Rojj Base
28    Tess Played
29      Reppy Red
30    Marry Toeey
31      Binn Rott
32      Kenn Rein
33       Gain Toe
34     Rows Noump
Name: name, dtype: object

In [ ]:
df[['name','mark']]

           name  mark
0      John Deo    75
1      Max Ruin    85
2        Arnold    55
3    Krish Star    60
4     John Mike    60
5     Alex John    55
6   My John Rob    78
7        Asruid    85
8       Tes Qry    78
9      Big John    55
10       Ronald    89
11        Recky    94
12          Kty    88
13         Bigy    88
14     Tade Row    88
15        Gimmy    88
16        Tumyu    54
17        Honny    75
18        Tinny    18
19       Jackly    65
20   Babby John    69
21       Reggid    55
22        Herod    79
23    Tiddy Now    78
24     Giff Tow    88
25       Crelea    79
26          NaN    81
27    Rojj Base    86
28  Tess Played    55
29    Reppy Red    79
30  Marry Toeey    88
31    Binn Rott    90
32    Kenn Rein    96
33     Gain Toe    69
34   Rows Noump    88

In [ ]:
df.head(3)

   id      name  class  mark  gender
0   1  John Deo   Four    75  female
1   2  Max Ruin  Three    85    male
2   3    Arnold  Three    55    male

In [ ]:
df['class']

35

In [ ]:
df.loc[:, "class", "four"]

IndexingError: Too many indexers

In [ ]:
df[df["class"] == "four"]

    id         name class  mark  gender
0    1     John Deo  four    75  female
1    2     Max Ruin  four    85    male
2    3       Arnold  four    55    male
3    4   Krish Star  four    60  female
4    5    John Mike  four    60  female
5    6    Alex John  four    55    male
6    7  My John Rob  four    78    male
7    8       Asruid  four    85    male
8    9      Tes Qry  four    78     NaN
9   10     Big John  four    55  female
10  11       Ronald  four    89  female
11  12        Recky  four    94  female
12  13          Kty  four    88  female
13  14         Bigy  four    88  female
14  15     Tade Row  four    88    male
15  16        Gimmy  four    88    male
16  17        Tumyu  four    54    male
17  18        Honny  four    75    male
18  19        Tinny  four    18    male
19  20       Jackly  four    65  female
20  21   Babby John  four    69  female
21  22       Reggid  four    55  female
22  23        Herod  four    79    male
23  24    Tiddy Now  four    78    male
24  25     Giff Tow  four    88    male
25  26       Crelea  four    79    male
26  27          NaN  four    81     NaN
27  28    Rojj Base  four    86  female
28  29  Tess Played  four    55    male
29  30    Reppy Red  four    79  female
30  31  Marry Toeey  four    88    male
31  32    Binn Rott  four    90  female
32  33    Kenn Rein  four    96  female
33  34     Gain Toe  four    69    male
34  35   Rows Noump  four    88  female

In [100]:
df["passed"] = df["mark"] >= 60
df

    id         name class  mark  gender  passed
0    1     John Deo  four    75  female    True
1    2     Max Ruin  four    85    male    True
2    3       Arnold  four    55    male   False
3    4   Krish Star  four    60  female    True
4    5    John Mike  four    60  female    True
5    6    Alex John  four    55    male   False
6    7  My John Rob  four    78    male    True
7    8       Asruid  four    85    male    True
8    9      Tes Qry  four    78     NaN    True
9   10     Big John  four    55  female   False
10  11       Ronald  four    89  female    True
11  12        Recky  four    94  female    True
12  13          Kty  four    88  female    True
13  14         Bigy  four    88  female    True
14  15     Tade Row  four    88    male    True
15  16        Gimmy  four    88    male    True
16  17        Tumyu  four    54    male   False
17  18        Honny  four    75    male    True
18  19        Tinny  four    18    male   False
19  20       Jackly  four    65  female    True
20  21   Babby John  four    69  female    True
21  22       Reggid  four    55  female   False
22  23        Herod  four    79    male    True
23  24    Tiddy Now  four    78    male    True
24  25     Giff Tow  four    88    male    True
25  26       Crelea  four    79    male    True
26  27          NaN  four    81     NaN    True
27  28    Rojj Base  four    86  female    True
28  29  Tess Played  four    55    male   False
29  30    Reppy Red  four    79  female    True
30  31  Marry Toeey  four    88    male    True
31  32    Binn Rott  four    90  female    True
32  33    Kenn Rein  four    96  female    True
33  34     Gain Toe  four    69    male    True
34  35   Rows Noump  four    88  female    True

In [103]:
df.rename(columns={"mark": "score"}, inplace=True)
df

    id         name class  score  gender  passed
0    1     John Deo  four     75  female    True
1    2     Max Ruin  four     85    male    True
2    3       Arnold  four     55    male   False
3    4   Krish Star  four     60  female    True
4    5    John Mike  four     60  female    True
5    6    Alex John  four     55    male   False
6    7  My John Rob  four     78    male    True
7    8       Asruid  four     85    male    True
8    9      Tes Qry  four     78     NaN    True
9   10     Big John  four     55  female   False
10  11       Ronald  four     89  female    True
11  12        Recky  four     94  female    True
12  13          Kty  four     88  female    True
13  14         Bigy  four     88  female    True
14  15     Tade Row  four     88    male    True
15  16        Gimmy  four     88    male    True
16  17        Tumyu  four     54    male   False
17  18        Honny  four     75    male    True
18  19        Tinny  four     18    male   False
19  20       Jackly  four     65  female    True
20  21   Babby John  four     69  female    True
21  22       Reggid  four     55  female   False
22  23        Herod  four     79    male    True
23  24    Tiddy Now  four     78    male    True
24  25     Giff Tow  four     88    male    True
25  26       Crelea  four     79    male    True
26  27          NaN  four     81     NaN    True
27  28    Rojj Base  four     86  female    True
28  29  Tess Played  four     55    male   False
29  30    Reppy Red  four     79  female    True
30  31  Marry Toeey  four     88    male    True
31  32    Binn Rott  four     90  female    True
32  33    Kenn Rein  four     96  female    True
33  34     Gain Toe  four     69    male    True
34  35   Rows Noump  four     88  female    True

In [109]:
df.drop(columns=["passed"], inplace=True)
df

    id         name class  score  gender
0    1     John Deo  four     75  female
1    2     Max Ruin  four     85    male
2    3       Arnold  four     55    male
3    4   Krish Star  four     60  female
4    5    John Mike  four     60  female
5    6    Alex John  four     55    male
6    7  My John Rob  four     78    male
7    8       Asruid  four     85    male
8    9      Tes Qry  four     78     NaN
9   10     Big John  four     55  female
10  11       Ronald  four     89  female
11  12        Recky  four     94  female
12  13          Kty  four     88  female
13  14         Bigy  four     88  female
14  15     Tade Row  four     88    male
15  16        Gimmy  four     88    male
16  17        Tumyu  four     54    male
17  18        Honny  four     75    male
18  19        Tinny  four     18    male
19  20       Jackly  four     65  female
20  21   Babby John  four     69  female
21  22       Reggid  four     55  female
22  23        Herod  four     79    male
23  24    Tiddy Now  four     78    male
24  25     Giff Tow  four     88    male
25  26       Crelea  four     79    male
26  27          NaN  four     81     NaN
27  28    Rojj Base  four     86  female
28  29  Tess Played  four     55    male
29  30    Reppy Red  four     79  female
30  31  Marry Toeey  four     88    male
31  32    Binn Rott  four     90  female
32  33    Kenn Rein  four     96  female
33  34     Gain Toe  four     69    male
34  35   Rows Noump  four     88  female